version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
      POSTGRES_DB: scheduler
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

