name: "Unit Test"

on:
  push:
    branches:
      - main
      - staging
    paths-ignore:
      - 'documentation/**'
      - '*.md'
      - 'docker-compose.yaml'
      - 'docker-compose.dev.yaml'
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...